<div class="simple-format-smiles round" id="simple-format-<?php echo $textarea_id;?>">
  <img src="./stuff/img/smiles/smiley-smile.gif" alt=":-)" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-smile.gif&quot; alt=&quot;smile&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-wink.gif" alt=";-)" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-wink.gif&quot; alt=&quot;wink&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-cool.gif" alt="8-)" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-cool.gif&quot; alt=&quot;cool&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-lol.gif" alt=":-D" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-lol.gif&quot; alt=&quot;lol&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-tongue.gif" alt=":-P" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-tongue.gif&quot; alt=&quot;tongue&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-love.gif" alt=":love:" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-love.gif&quot; alt=&quot;love&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-grin.gif" alt=":-)))" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-grin.gif&quot; alt=&quot;grin&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-jokingly.gif" alt="8-D" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-jokingly.gif&quot; alt=&quot;jokingly&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-kiss.gif" alt=":-*" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-kiss.gif&quot; alt=&quot;kiss&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-surprised.gif" alt="8-O" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-surprised.gif&quot; alt=&quot;surprised&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-cry.gif" alt=";,-(" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-cry.gif&quot; alt=&quot;cry&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-stop.gif" alt="stop" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-stop.gif&quot; alt=&quot;stop&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-sad.gif" alt=":-(" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-sad.gif&quot; alt=&quot;sad&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-undecided.gif" alt="undecided" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-undecided.gif&quot; alt=&quot;undecided&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-zzz.gif" alt="zzz" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-zzz.gif&quot; alt=&quot;zzz&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-evil.gif" alt="]:->" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-evil.gif&quot; alt=&quot;evil&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-ninja.gif" alt="ninja" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-ninja.gif&quot; alt=&quot;ninja&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-whistle.gif" alt="whistle:" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-whistle.gif&quot; alt=&quot;whistle&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-angry.gif" alt=":-<" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-angry.gif&quot; alt=&quot;angry&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-fuck.gif" alt="fuck" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-fuck.gif&quot; alt=&quot;fuck&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-pirate.gif" alt="beer" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-pirate.gif&quot; alt=&quot;pirate&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-what.gif" alt="what" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-what.gif&quot; alt=&quot;what&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-yes.gif" alt="yes" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-yes.gif&quot; alt=&quot;yes&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-no.gif" alt="no" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-no.gif&quot; alt=&quot;no&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
  <img src="./stuff/img/smiles/smiley-beer.gif" alt="beer" height="16" width="16" onclick="insert_value('<img src=&quot;<?php echo $conf['admin_url'];?>/stuff/img/smiles/smiley-beer.gif&quot; alt=&quot;beer&quot; height=&quot;16&quot; width=&quot;16&quot; />', document.getElementById('<?php echo $textarea_id;?>'));" />
</div>
<p class="simple-format">
  <img src="./stuff/img/icons/text-bold.png" alt="Bold text" height="16" width="16" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<strong>', '</strong>', '')" />
  <img src="./stuff/img/icons/text-italic.png" alt="Italics" height="16" width="16" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<em>', '</em>', '')" />
  <img src="./stuff/img/icons/text-link.png" alt="Link" height="16" width="16" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<a href=&quot;http://&quot;>', '</a>', '')" />
  <img src="./stuff/img/icons/text-align-left.png" alt="Text align left" height="16" width="16" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<p style=&quot;text-align: left;&quot;>', '</p>', '')" />
  <img src="./stuff/img/icons/text-align-center.png" alt="Text align center" height="16" width="16" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<p style=&quot;text-align: center;&quot;>', '</p>', '')" />
  <img src="./stuff/img/icons/text-align-right.png" alt="Text align right" height="16" width="16" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<p style=&quot;text-align: right;&quot;>', '</p>', '')" />
  <img src="./stuff/img/icons/text-align-justify.png" alt="Text align justify" height="16" width="16" class="last_img" onclick="mark_bbtext('<?php echo $textarea_id;?>', '<p style=&quot;text-align: justify;&quot;>', '</p>', '')" />
  <img src="./stuff/img/smiles/smiley-wink.gif" alt=":-)" title="<?php echo $lang['news_insert_emoticon'];?>" height="16" width="16" class="toggle" rel="simple-format-<?php echo $textarea_id;?>" />
</p>
